# Generated by Django 2.0 on 2017-03-14 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogentry',
            options={'verbose_name_plural': 'blog entries'},
        ),
    ]
