# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogEntryPriority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.BooleanField(help_text='Is this entry high priority?')),
                ('blog_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.BlogEntry')),
            ],
        ),
    ]
